// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lvmendes.Entidades;

namespace lvmendes.Entidades.Migrations
{
    [DbContext(typeof(EFDataContext))]
    [Migration("20191029005527_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lvmendes.Entidades.Autorizacoes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Autorizacao","dbo");
                });

            modelBuilder.Entity("lvmendes.Entidades.Perfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AutorizacoesId");

                    b.Property<long?>("SistemaId");

                    b.HasKey("Id");

                    b.HasIndex("AutorizacoesId");

                    b.HasIndex("SistemaId");

                    b.ToTable("Perfil","dbo");
                });

            modelBuilder.Entity("lvmendes.Entidades.Sistema", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Sistema","dbo");
                });

            modelBuilder.Entity("lvmendes.Entidades.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AutorizacoesId");

                    b.Property<string>("Email");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.HasIndex("AutorizacoesId");

                    b.ToTable("Usuario","dbo");
                });

            modelBuilder.Entity("lvmendes.Entidades.Perfil", b =>
                {
                    b.HasOne("lvmendes.Entidades.Autorizacoes")
                        .WithMany("Perfils")
                        .HasForeignKey("AutorizacoesId");

                    b.HasOne("lvmendes.Entidades.Sistema", "Sistema")
                        .WithMany()
                        .HasForeignKey("SistemaId");
                });

            modelBuilder.Entity("lvmendes.Entidades.Usuario", b =>
                {
                    b.HasOne("lvmendes.Entidades.Autorizacoes", "Autorizacoes")
                        .WithMany()
                        .HasForeignKey("AutorizacoesId");
                });
#pragma warning restore 612, 618
        }
    }
}
